ctrnacty sraz
PyLadiesCZ/roboprojekt-blog pull request #31
Opened 2019-01-18 20:16 UTC by ivet1987

2019-01-18 20:45 UTC, encukou commented on content/2019-01-15_ctrnacty-sraz-vysvetlovani.md
> + ![github](./images/github.jpg
```suggestion
 ![github](./images/github.jpg)
```

2019-01-18 21:50 UTC, anezkamll requested changes
Navrhuji dvě malé úpravy, jinak za mě ok.

2019-01-18 21:50 UTC, anezkamll commented on content/2019-01-15_ctrnacty-sraz-vysvetlovani.md
> +Začaly jsme souborem *util.py* a procházely metodu po metodě jednotlivých tříd. Vášnivá diskuze nastala u třídy HoleTile, která volá metodu robota – robot.die(). Původně bylo v kódu napsáno, že si ro
pro "robot.die()" bych použila `robot.die()`, je to kus kódu, tak ať je to vidět

2019-01-18 21:50 UTC, anezkamll commented on content/2019-01-15_ctrnacty-sraz-vysvetlovani.md
> +Začaly jsme souborem *util.py* a procházely metodu po metodě jednotlivých tříd. Vášnivá diskuze nastala u třídy HoleTile, která volá metodu robota – robot.die(). Původně bylo v kódu napsáno, že si ro
Tohle: "Nyní je to tedy metoda políčka vyvolá metodu robota" jako věta nedává moc smysl, napsala bych buď "Nyní je to tedy tak, že metoda políčka vyvolá metodu robota", nebo jen "Nyní tedy metoda políčka vyvolá metodu robota"

2019-01-19 16:22 UTC, ivet1987 commented
@anezkamll  opraveno

2019-01-20 09:27 UTC, anezkamll approved these changes

2019-01-20 09:50 UTC, merged