šestnáctý sraz
PyLadiesCZ/roboprojekt-blog pull request #36
Opened 2019-02-18 08:52 UTC by ivet1987

2019-02-19 12:17 UTC, befeleme requested changes

2019-02-19 12:17 UTC, befeleme commented on content/2019-02-05_sestnacty-sraz.md
> +if distance < 0:
Tomuto odstavci nerozumim a přiložené foto nepomáhá pochopit, kde ten problém přesně je (mám odzkoušené všechny směry + posouvání ostatních robotů v cestě, a na žádný problém jsem nenarazila). Můžeš to přesněji popsat?

2019-02-19 20:54 UTC, ivet1987 commented on content/2019-02-05_sestnacty-sraz.md
> +if distance < 0:
Přepis záznamu: Řekneš robotovi jsi o -1 na západ, tak dle kódu se první otočí U_TURN , tedy na jih, což je blbě, druhý krok popojde a třetí krok že se opět U_TURN otočí a kouká na sever. viz obrázek.  Takže se poprvé otočí špatně a nepůjde na ten západ, ale na jih.

2019-02-22 21:39 UTC, ivet1987 commented on content/2019-02-05_sestnacty-sraz.md
> +if distance < 0:
Chceš to jako presne popsat i do toho blogu nebo ti stačí vysvětlení takto v komentáři? Jestli jo, prosim o schvaleni

2019-02-23 17:03 UTC, befeleme commented on content/2019-02-05_sestnacty-sraz.md
> +if distance < 0:
Ahoj, musím říct, že pořád nerozumím, a tak si nejsem úplně jistá, jestli je to dobrý odstavec od blogpostu. Ráda bych, aby se ozval i někdo jiný.

2019-02-24 16:39 UTC, anezkamll commented on content/2019-02-05_sestnacty-sraz.md
> +if distance < 0:
On cely tady ten post je dost slozity, tak nevim. Jak se vaze primo na kod... Ale urcite je lepsi detailnejsi popis ze zaznamu. Ten, co je v postu, nic moc nerika.

2019-02-24 16:41 UTC, anezkamll requested changes

2019-02-24 16:41 UTC, anezkamll commented on content/2019-02-05_sestnacty-sraz.md
> +Políčka (`Tile`) by měla jako `properties` dostat slovník jako např. `{'crossroads': True, 'direction': 90, 'count': 2} a neměla by ignorovat jména vlastností.
Tady je chyba, za slozenymi zavorkami chybi `, takze pak nasledujici radky soubor vidi jako cast ukazky kodu.

2019-02-26 10:07 UTC, ivet1987 commented on content/2019-02-05_sestnacty-sraz.md
> +if distance < 0:
opraveno

2019-02-26 10:07 UTC, ivet1987 commented
Doplněno za oba opakovací srazy.

2019-02-26 12:53 UTC, encukou commented on content/2019-02-05_sestnacty-sraz.md
> +Políčka (`Tile`) by měla jako `properties` dostat slovník jako např. `{'crossroads': True, 'direction': 90, 'count': 2} a neměla by ignorovat jména vlastností.
```suggestion
Políčka (`Tile`) by měla jako `properties` dostat slovník jako např. `{'crossroads': True, 'direction': 90, 'count': 2}` a neměla by ignorovat jména vlastností.
```

2019-02-26 12:53 UTC, encukou commented on content/2019-02-05_sestnacty-sraz.md
> +V metodě ` def_inactive(self)` jsou jako souřadnice neaktivního robota použity `(-1, -1)` . Nedávají nikdy smysl jako čísla (x, y), nutno změnit na `None`, protože robot v té chvíli není na hrací plo
```suggestion
V metodě `def_inactive(self)` jsou jako souřadnice neaktivního robota použity `(-1, -1)` . Nedávají nikdy smysl jako čísla (x, y), nutno změnit na `None`, protože robot v té chvíli není na hrací ploše.
```

2019-02-26 12:53 UTC, encukou commented on content/2019-02-05_sestnacty-sraz.md
> +V backendu ve vlastnostech robota se objevuje `  self.path = path` a `self.path_front = path_front`. Jelikož se jedná o cestu k obrázkům, patří to do frontedu a pokud to chceme propojit, je vhodné mí
```suggestion
V backendu ve vlastnostech robota se objevuje `self.path = path` a `self.path_front = path_front`. Jelikož se jedná o cestu k obrázkům, patří to do frontedu a pokud to chceme propojit, je vhodné místo toho robota pojmenovat.
```

2019-02-26 12:53 UTC, encukou commented on content/2019-02-05_sestnacty_sedmnacty_sraz.md
> +V backendu ve vlastnostech robota se objevuje `  self.path = path` a `self.path_front = path_front`. Jelikož se jedná o cestu k obrázkům, patří to do frontedu a pokud to chceme propojit, je vhodné mí
```suggestion
V backendu ve vlastnostech robota se objevuje `self.path = path` a `self.path_front = path_front`. Jelikož se jedná o cestu k obrázkům, patří to do frontedu a pokud to chceme propojit, je vhodné místo toho robota pojmenovat.
```

2019-02-26 12:53 UTC, encukou commented on content/2019-02-05_sestnacty_sedmnacty_sraz.md
> +V metodě ` def_inactive(self)` jsou jako souřadnice neaktivního robota použity `(-1, -1)` . Nedávají nikdy smysl jako čísla (x, y), nutno změnit na `None`, protože robot v té chvíli není na hrací plo
```suggestion
V metodě `def_inactive(self)` jsou jako souřadnice neaktivního robota použity `(-1, -1)` . Nedávají nikdy smysl jako čísla (x, y), nutno změnit na `None`, protože robot v té chvíli není na hrací ploše.
```

2019-02-26 12:53 UTC, encukou commented on content/2019-02-05_sestnacty_sedmnacty_sraz.md
> +Kód ve funkcích `def get_starting_coordinates(board)` a ` def get_robot_paths()` obsahuje načítání obrázků, což má být ve frontendu, takže vyřešit pojmenováním robotů a políček. Bylo by hezké mít sou
```suggestion
Kód ve funkcích `def get_starting_coordinates(board)` a `def get_robot_paths()` obsahuje načítání obrázků, což má být ve frontendu, takže vyřešit pojmenováním robotů a políček. Bylo by hezké mít soubor (json) s informacemi o robotech, kteří jsou na začátku hry na výběr a jména robotů načítat z něj. `get_robot_paths()` se změní na `get_robot_names()`.
```

2019-02-26 12:53 UTC, encukou commented on content/2019-02-05_sestnacty_sedmnacty_sraz.md
> +` self.power_down = not self.power_down`
```suggestion
`self.power_down = not self.power_down`
```

2019-02-27 19:27 UTC, anezkamll submitted a review, later dismissed

2019-02-28 08:55 UTC, befeleme commented
Jestli dobre vidim, jsou k zacnleneni dva posty - jeden sestnacty, jeden sestnacty-sedmnacty. Mam pocit, ze to neni spravne, a chceme zaclenit jen ten druhy post? Oprav, me @ivet1987, jestli neni tomu tak. 
Pak ze sve branche odstran ten sestnacty - proste ho smaz, a vysledek opet commitni.

2019-02-28 10:32 UTC, anezkamll commented
> Jestli dobre vidim, jsou k zacnleneni dva posty - jeden sestnacty, jeden sestnacty-sedmnacty. 

To je vtipné, jsem zkontrolovala jen úpravu mnou navrhovaných změn a tohle jsem úplně odignorovala... OMG *facepalm*

2019-02-28 17:51 UTC, ivet1987 commented
Jéé já myslela že se mi to sloučilo, už opraveno. @befeleme

2019-03-01 06:57 UTC, befeleme approved these changes

2019-03-01 06:58 UTC, merged