Add post from last session
PyLadiesCZ/roboprojekt-blog pull request #57
Opened 2019-11-27 21:20 UTC by anezkamll

2019-11-27 22:05 UTC, ivet1987 commented on content/2019-11-26_posledni-sraz.md
> +Vtéto sestavě jsme vyzykoušeli dvě mapy.
```suggestion
V této sestavě jsme vyzkoušeli dvě mapy.
```

2019-11-27 22:06 UTC, ivet1987 commented on content/2019-11-26_posledni-sraz.md
> +Takováto mapa by byla obtížná i v menším počtu hráčů, ale v sedmi lidech na ní bylo prakticky nemožné vyhrát.
```suggestion
Taková mapa by byla obtížná i v menším počtu hráčů, ale v sedmi lidech na ní bylo prakticky nemožné vyhrát.
```

2019-11-27 22:07 UTC, ivet1987 commented on content/2019-11-26_posledni-sraz.md
> +Roboprojekt byl experiementální kurz.
```suggestion
Roboprojekt byl experimentální kurz.
```

2019-11-28 08:07 UTC, ivet1987 approved these changes

2019-11-28 08:07 UTC, merged

2019-11-28 08:08 UTC, befeleme requested changes
Ještě pidimaličkost

2019-11-28 08:08 UTC, befeleme commented on content/2019-11-26_posledni-sraz.md
> +Na začátku jsme ještě doplily poslední důležitou věc, možnost nastavení nižšího počtu hráčů i v mapách pro více hráčů a pak už nic nebránilo testování hry.
```suggestion
Na začátku jsme ještě doplnily poslední důležitou věc, možnost nastavení nižšího počtu hráčů i v mapách pro více hráčů a pak už nic nebránilo testování hry.
```

2019-11-28 08:09 UTC, anezkamll commented on content/2019-11-26_posledni-sraz.md
> +Na začátku jsme ještě doplily poslední důležitou věc, možnost nastavení nižšího počtu hráčů i v mapách pro více hráčů a pak už nic nebránilo testování hry.
Ivet už to mergnula 😄